---
- hosts: prod
  user: root
  sudo: no
  gather_facts: no

  tasks:
  - name: deb package list is up-to-date
    command: apt-get update
    tags: base-software

  - name: python3 is installed
    apt: name=python3 state=present
    tags: base-software

